# Generated by Django 3.1.1 on 2021-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='work_done',
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_hours',
            field=models.PositiveIntegerField(default=0, help_text='Maximum target hours is 20', verbose_name='Target hours needed'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='work_started',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Work started'),
        ),
    ]
