# Generated by Django 3.1.1 on 2021-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20210510_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='target_hours',
            field=models.PositiveIntegerField(default=0, help_text='Maximum target hours is 20'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='time_left',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='work_started',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_spent',
            field=models.TimeField(null=True),
        ),
    ]
