# Generated by Django 3.1.2 on 2021-04-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210321_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCalories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('started', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('total_calories', models.PositiveIntegerField(default=0, verbose_name='Total calories')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Day calories',
                'verbose_name_plural': 'Days calories',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('time', models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER'), ('SNACK', 'SNACK')], max_length=10)),
                ('grams', models.PositiveIntegerField(default=0)),
                ('calories_per_gram', models.PositiveIntegerField(default=0, verbose_name='Calories per gram')),
                ('day_calories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='health.daycalories', verbose_name='Related day')),
            ],
        ),
    ]
