# Generated by Django 3.1.2 on 2021-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_points',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
