# Generated by Django 3.1.2 on 2021-05-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210321_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_money',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
        ),
    ]
