# Generated by Django 3.1.2 on 2021-03-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210321_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySpendingsEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('started', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total spent')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total earned')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Day spendings and earnings',
                'verbose_name_plural': 'Days spendings and earnings',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('more_details', models.CharField(blank=True, help_text='Optional', max_length=75, verbose_name='More details')),
                ('part_of_plan', models.BooleanField(default=False, verbose_name='Part of a plan')),
                ('day_number', models.PositiveIntegerField(default=0, help_text='Plan required', verbose_name='Day number ( plan )')),
                ('priority', models.BooleanField(default=False)),
                ('day_spend_earn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to='wallet.dayspendingsearnings', verbose_name='Day spendings and earnings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanSpendings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('Type', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=8, verbose_name='Plan Type')),
                ('spendings', models.ManyToManyField(blank=True, null=True, to='wallet.Spending')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Spending plan',
                'verbose_name_plural': 'Spending plans',
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('more_details', models.CharField(blank=True, help_text='Optional', max_length=75, verbose_name='More details')),
                ('day_spend_earn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='wallet.dayspendingsearnings', verbose_name='Day spendings and earnings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
